### ISSUE TITLE
admin login 

### ISSUE THREAD

**Issue by hakanngul** [gentritabazi01/vuejs-soft-ui-dashboard#2]
what is the admin page user information ?

**Comment by gentritabazi** [comment]
Sorry, question is not clear ?

**Comment by hakanngul** [comment]
i mean i just want to look your repo but i can't login 

![image](https://user-images.githubusercontent.com/34252239/124440718-97132280-dd83-11eb-8cb6-f9808c3c04fe.png)

**Comment by hakanngul** [comment]
![image](https://user-images.githubusercontent.com/34252239/124440884-c9248480-dd83-11eb-9b32-cf6849e425e4.png)

**Comment by gentritabazi** [comment]
Yes because you need to connect with backend.

But you can skip this step by removing `auth` middleware for route `admin.dashboard`.

**Comment by gentritabazi** [comment]
Check last commit i made.

**Comment by hakanngul** [comment]
Sorry I'm new on the VueJS i didn't see :))
