### ISSUE TITLE
27 Vulnerabilities

### ISSUE THREAD

**Issue by JJordan0C** [gentritabazi01/vuejs-soft-ui-dashboard#5]
I've installed all dependencies, and now i've 18 High vulnerabilities and 8 moderate and 1 low, this Is normal?
![EJS](https://user-images.githubusercontent.com/69581081/167099827-f6e6e9b6-fcbd-4214-983b-4e099696f88d.PNG)
![Glob-Parent](https://user-images.githubusercontent.com/69581081/167099850-012c3d6f-2da7-48ab-92b4-a5a5b8040391.PNG)
![Other](https://user-images.githubusercontent.com/69581081/167099875-93b50fdb-6b92-4069-a3a3-a86b97af6de3.PNG)

**Comment by gentritabazi** [comment]
Yes!
